version: 2
jobs:
  build:
    environment:
      CONTAINER_NAME: "quay.io/redsift/ingraind-build"
      KERNEL_VERSION: "4.16.12-1.el7.elrepo.x86_64"

    working_directory: /tmp/ws/build
    docker:
      - image: docker:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/ws

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to a regsitry
          command: |
            echo ${QUAY_PASS} | docker login --username ${QUAY_USER} --password-stdin quay.io

      - run:
          name: Build Docker image
          command: |
            export TAG=${CIRCLE_TAG:-unknown}
            export SHA=${CIRCLE_SHA1:0:7}
            docker build --no-cache \
                         -f Dockerfile.18.04 \
                         --build-arg kernel=kernels/$KERNEL_VERSION \
                         -t $CONTAINER_NAME:18.04 \
                         -t $CONTAINER_NAME:$SHA-18.04 \
                         .

            docker build --no-cache \
                         -f Dockerfile.19.10 \
                         --build-arg kernel=kernels/$KERNEL_VERSION \
                         -t $CONTAINER_NAME:latest \
                         -t $CONTAINER_NAME:19.10 \
                         -t $CONTAINER_NAME:$SHA-19.10 \
                         .

            echo "Total sizes"
            docker images $CONTAINER_NAME
            docker push $CONTAINER_NAME:18.04
            docker push $CONTAINER_NAME:19.10

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - build

  build_pack:
    jobs:
      - build
