name: Docker

on:
  push:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/foniod-build
  MAIN_BRANCH: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up version information
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "$MAIN_BRANCH" ] && VERSION=latest
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Build Ubuntu 21.04
        id: ubuntu2104
        run: |
          VERSION=${{ env.version }}-ubuntu-21.04
          docker build --no-cache \
                       -f Dockerfile.21.04 \
                       -t $IMAGE_NAME:$VERSION \
                       .
          echo "::set-output name=image_id::$IMAGE_NAME:$VERSION"

      - name: Build Ubuntu 20.04
        id: ubuntu2004
        run: |
          VERSION=${{ env.version }}-ubuntu-20.04
          docker build --no-cache \
                       -f Dockerfile.20.04 \
                       -t $IMAGE_NAME:$VERSION \
                       .
          echo "::set-output name=image_id::$IMAGE_NAME:$VERSION"

      - name: Build Ubuntu 18.04
        id: ubuntu1804
        run: |
          VERSION=${{ env.version }}-ubuntu-18.04
          docker build --no-cache \
                       -f Dockerfile.18.04 \
                       -t $IMAGE_NAME:$VERSION \
                       .
          echo "::set-output name=image_id::$IMAGE_NAME:$VERSION"

      - name: Build Fedora 34
        id: fedora34
        run: |
          VERSION=${{ env.version }}-fedora-34
          docker build --no-cache \
                       -f Dockerfile.fedora-34 \
                       -t $IMAGE_NAME:$VERSION \
                       .
          echo "::set-output name=image_id::$IMAGE_NAME:$VERSION"

      - name: Build Alpine 3.14
        id: alpine314
        run: |
          VERSION=${{ env.version }}-alpine
          docker build --no-cache \
                       -f Dockerfile.alpine \
                       -t $IMAGE_NAME:$VERSION \
                       .
          echo "::set-output name=image_id::$IMAGE_NAME:$VERSION"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker push ${{ steps.ubuntu2104.outputs.image_id }}
          docker push ${{ steps.ubuntu2004.outputs.image_id }}
          docker push ${{ steps.ubuntu1804.outputs.image_id }}
          docker push ${{ steps.fedora34.outputs.image_id }}
          docker push ${{ steps.alpine314.outputs.image_id }}
